services:
  db:
    image: postgres:16
    container_name: library_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./app
    container_name: library_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://admin:admin@db:5432/library_db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
